version: '2'
services:
  monitoring:
    image: nicolargo/glances:3.2.5-full
    container_name: glances-3.2.5
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./wordpress-mdb-pma/carpetacontenedora:/wordpress-data:ro 
      - ./wordpress-mdb-pma/data:/wordpress-db:ro#wp folder 
      - ./glances/glances.conf:/glances/conf/glances.conf
    environment:
      - GLANCES_OPT=-w
    ports:
      - 61208-61209:61208-61209
    hostname: Ubuntu Server

#Sin docker compose:
#
##docker run -d --name=glances --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /home/guille/Software/glances/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host nicolargo/glances:3.2.5-full

  postgres:
    container_name: postres-GUAC
    image: postgres:12.2
    restart: always
    volumes:
      - ./guacamole/init:/docker-entrypoint-initdb.d
      - ./guacamole/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db

  guacd:
    container_name: guacd-GUAC
    image: guacamole/guacd:1.3.0
    restart: always

  guac:
  
    container_name: guac-GUAC
    image: guacamole/guacamole:1.3.0
    restart: always
    ports:
      - "6060:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd
  
  db:
    image: mariadb:10.3.9
    volumes:
      - ./wordpress-mdb-pma/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=secret   
    networks:
      - wordpress
  
  web:
      image: wordpress:5.9
      depends_on:
        - db
      volumes:
        - ./wordpress-mdb-pma/carpetacontenedora:/var/www/html
      environment:
        - WORDPRESS_DB_USER=manager
        - WORDPRESS_DB_PASSWORD=secret
        - WORDPRESS_DB_HOST=db
      ports:
        - 3333:80
      networks:
      - wordpress

  pma:
      depends_on:
        - db
      image: phpmyadmin
     # container_name: phpmyadmin_web
      restart: always
      ports:
        - 9999:80
      networks:
      - wordpress

volumes:
  data:
networks:
  wordpress:
