version: '3.3'

services:

  postgres:
    container_name: postres-GUAC
    image: postgres:12.2
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db

  guacd:
    container_name: guacd-GUAC
    image: guacamole/guacd:1.3.0
    restart: always

  guac:
    container_name: guac-GUAC
    image: guacamole/guacamole:1.3.0
    restart: always
    ports:
      - "6060:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd
