version: '2'
services:
  monitoring:
    image: nicolargo/glances:3.2.5-full
    container_name: glances-3.2.5
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/grupo/proyecto/docker-ct/wordpress-mdb-pma/carpetacontenedora:/wordpress-data:ro 
      - /home/grupo/proyecto/docker-ct/wordpress-mdb-pma/data:/wordpress-db:ro#wp folder 
      - ./glances.conf:/glances/conf/glances.conf
    environment:
      - GLANCES_OPT=-w
    ports:
      - 61208-61209:61208-61209
    hostname: Ubuntu Server

#Sin docker compose:
#
##docker run -d --name=glances --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /home/guille/Software/glances/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host nicolargo/glances:3.2.5-full
