version: '2'
services:
  monitoring:
    image: nicolargo/glances:3.2.5-full
    container_name: glances-3.2.5
    restart: always
    pid: host
    volumes:
      - /home/guille:/home/guille:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/guille/Software/glances/glances.conf:/glances/conf/glances.conf
      - /home/guille/Software/sftpgo_docker/home/data/:/sftpgo:ro
    environment:
      - GLANCES_OPT=-w
    ports:
      - 61208-61209:61208-61209
    hostname: Raspberry PI 4 de Guille

#Sin docker compose:
#
##docker run -d --name=glances --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /home/guille/Software/glances/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host nicolargo/glances:3.2.5-full
